ubuntu-flutter-community/musicpod

lib/app/common/audio_page.dart, pubspec.yaml
As suggested wrapped inside a HTML. Clicking opens a dialog with the full description
Fixes #17
=> FIx: HTML tags in podcast description shows as text

snap/snapcraft.yaml
This reverts commit e747533fe55796d8978a3566d201edb5c0e31777.
As a temp fix until we know what causes the problem in edge 
Tested in a fresh lunar VM as well and the error still exists
=> Revert "Don't stage libmfx1 on arm64 as it's amd64 only.  Fixes #35 (#48)"

lib/app/local_audio/local_audio_model.dart, lib/app/music_app.dart
Previously, any failure to load the metadata for any audio file would stop loading the entire music collection. This PR makes it so that, instead of dying, it just prints out the error and skips that file.
Should I change this so that it shows a toast of some sort with a message of "Failed to load &lt;file path&gt;" instead?
=> Don't die on FFI exceptions

lib/app/app.dart, lib/app/local_audio/failed_imports_content.dart, lib/app/local_audio/local_audio_model.dart, lib/app/local_audio/local_audio_page.dart, lib/l10n/app_en.arb, lib/main.dart, lib/musicpod.dart, lib/service/local_audio_service.dart
- moves file loading into a service class
- directory and audios are stored there
- took this as a chance to get any material component import out of the local audio model
CC @aleksrutins
=> Move file loading out of the Widget tree

snap/snapcraft.yaml
The real workaround here is to call "dart pub get" rather than "flutter pub get" but to do this we need to move away from using the flutter plugin in snapcraft to get a more complete build environment.
=> Switch to flutter-git to work around build service issues

.github/workflows/snap.yaml
Hi @kenvandine :wave: :smile_cat: 
Really would try this continuos delivery deployment on github instead of doing this on snapcraft
I followed https://snapcraft.io/docs/snapcraft-authentication
and
https://github.com/snapcore/action-build
and
https://github.com/snapcore/action-publish
Would be nice if you could try if I made any mistake
=> Add publish action

appimage.sh, snap/gui/musicpod.desktop
Here's a bash script for creating appimage.
``~/Applications/appimagetool`` at line 38 is the path that appimagetool place itself via gearlevel or Appimage installation in general. So maybe that one should be changed.
This can be added to github workflow to build appimage version.
=> AppImage generation

snap/gui/musicpod.desktop
This is needed so that the dash/dock can recognize the appropriate icon when the app is running and enables pinning the app to the dash/dock.
StartupWMClass=musicpod
musicpod should be the name of the binary that is running
=> Add StartupWMClass

lib/src/player/player_service.dart
The index of the next song was not updated, when we change the song. As a result, each song, that's played by pressing the previous button, will play again, if we press the next button. What this PR does is, sets audio index, to the previous song of the current audio. Then updates the index of the next song. Not sure about this, but I think we should not return if the next song is null.
fixes #382
=> [service]: fix the previous button 

lib/constants.dart, lib/src/app/app.dart, lib/src/app/app_model.dart, lib/src/app/master_detail_page.dart, lib/src/app/master_item.dart, lib/src/app/master_items.dart, lib/src/common/master_tile.dart, lib/src/library/library_model.dart, lib/src/local_audio/local_audio_page.dart, lib/src/player/player_model.dart, lib/src/player/player_track.dart, lib/src/player/player_view.dart, lib/src/podcasts/podcasts_page.dart, lib/src/radio/radio_page.dart
- move complicated build logic outside of master detail page
- give playertrack times height to avoid repaint of the whole app
- move fullscreen get/set to appmodel
- give all master items pageIDs
=> Refactor to reduce repaints

lib/src/local_audio/local_audio_model.dart
As a start sort AlbumView by Audio.album and ArtistView by Audio.artist
Ref #503
=> LocalAudio: sort artists and albums

lib/src/common/audio_filter.dart
When comparing strings that contain numbers, `compareTo` method gives results like `1, 10, 11, 2...`. This is technically correct, but unnatural.
I have to admit that my solution is not elegant, so I understand if this PR will be closed without merging, <del>but I couldn't think of anything better than replacing numbers with `a` and `b` characters in strings to compare if they both contain numbers.</del> (found another solution that I hope is better)
Before:
After:
Related: #503
=> Improve sorting of strings that contain numbers

.github/workflows/appimage.yml, .github/workflows/snap.yaml
- the snapcraft CD is reliable now for both amd64 and arm64, thus disabling snap build/publish on main push, as this is automatically taken care of by snapcraft
- disabled appimage action, to make a new github action in the future which is triggered by a git tag and then creates appimage, exe and dmg artifacts
=> Temp disable release github actions

lib/src/player/player_view.dart
otherwise the window background shines through, which is different on each platform
=> Wrap sidebar player divider in material

lib/src/app/app.dart, lib/src/local_audio/local_audio_model.dart, lib/src/local_audio/view/failed_imports_content.dart, lib/src/local_audio/view/local_audio_page.dart, lib/src/player/player_mixin.dart, lib/src/settings/view/settings_page.dart
If users have small local audio libs this will hardly be visible. If users have huge local libs they will probably use MusicPod a lot for local audios and will land here sooner or later. So do this right away to avoid an uninitialized LocalAudioModel.
=> Init local audio model early

android/app/src/debug/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml, lib/src/player/player_model.dart, lib/src/player/player_service.dart, lib/src/podcasts/view/audio_progress.dart, lib/src/podcasts/view/avatar_with_progress.dart, lib/src/podcasts/view/podcast_audio_tile.dart, lib/src/podcasts/view/sliver_podcast_page_list.dart, pubspec.lock, pubspec.yaml
- use audio_service_mpris instead of the mpris pub library
- fix last positions not being saved
- enqueue more podcasts on a single tile click
- change macOS & android audio controls depending on podcast/radio/local
Fixes #774
=> Player service improvements

lib/l10n/app_en.arb
In two messages, there's a double apostrophe. 
This gets rendered in the UI, which looks wrong. 
I hope me 'fixing' this isn't breaking 'escaping' anything.
=> Shrink double apostrophe's.

lib/app/view/master_detail_page.dart, lib/common/view/audio_page_header_html_description.dart, lib/common/view/audio_tile_option_button.dart, lib/common/view/icy_image.dart, lib/local_audio/view/local_audio_page.dart, lib/patch_notes/patch_notes_dialog.dart, lib/player/view/queue_button.dart, lib/playlists/view/playlist_page.dart, lib/podcasts/view/podcast_audio_tile.dart, lib/radio/view/radio_history_tile.dart, lib/settings/view/settings_tile.dart, pubspec.lock, pubspec.yaml
Import `flutter_animated_dialog` and use the `showAnimatedDialog` method instead of `showDialog`.
Note that you should avoid setting `barrierDismissible` to `true` if possible. Multiple clicks on the button calling the showAnimatedDialog method can lead to the following exception:
`FlutterError: Duplicate GlobalKey detected in widget tree.`
=> Add animation effects to the dialog.

lib/player/player_service.dart, pubspec.lock, pubspec.yaml
=> fix: some title of radio is html format, need to convert to human readable format

.github/workflows/release.yml, lib/common/view/audio_page_header_html_description.dart, lib/common/view/theme.dart, lib/local_audio/cover_store.dart, lib/local_audio/local_audio_service.dart, lib/player/view/player_remote_source_image.dart, lib/podcasts/view/podcast_page.dart
Also: hopefully fix release.yml + remove unused variables, constants and image cache read/write
=> fix: constrain podcast html descriptions

lib/constants.dart, lib/extensions/build_context_x.dart, lib/l10n/app_de.arb, lib/l10n/app_en.arb, lib/library/library_model.dart, lib/library/library_service.dart, lib/main.dart, lib/persistence_utils.dart, lib/podcasts/download_model.dart, lib/podcasts/view/download_button.dart, lib/settings/settings_model.dart, lib/settings/settings_service.dart, lib/settings/view/settings_page.dart, needs_translation.json
=> feat: let users select the downloads directory

lib/app/view/mobile_bottom_bar.dart, lib/common/data/player_state.dart, lib/constants.dart, lib/player/player_model.dart, lib/player/player_service.dart, lib/player/view/playback_rate_button.dart
=> fix: Playback Speed Setting Not Retained Between Sessions

lib/app/view/master_tile.dart, lib/common/data/audio.dart, lib/local_audio/local_audio_model.dart, lib/local_audio/local_audio_view.dart, lib/local_audio/view/local_audio_body.dart, lib/search/view/sliver_local_search_results.dart
=> chore: disable album artists until lib fix

lib/common/view/icons.dart, lib/l10n/app_en.arb, lib/persistence_utils.dart, lib/player/player_model.dart, lib/player/player_service.dart, lib/player/view/bottom_player.dart, lib/player/view/full_height_player_top_controls.dart, lib/player/view/player_main_controls.dart, lib/podcasts/view/podcast_page.dart, needs_translation.json
=> feat: mark podcast episodes as played

.github/workflows/snap.yml
Reactivate the snap creation from github actions, because finally github supports linux arm runners, too. Thus snapcraft is no longer needed (hopefully), also because the auto snap creation trigger seems to be bugged on snapcraft.
=> chore: reactivate_snap_creation

lib/extensions/string_x.dart, lib/player/player_service.dart, lib/player/view/player_title_and_artist.dart, lib/podcasts/view/podcast_page_header.dart, lib/podcasts/view/podcast_page_title.dart, lib/podcasts/view/podcasts_collection_body.dart
Closes #1261 
This commit introduces a new extension getter `unEscapeHtml` to unescape html entities from strings using
`HtmlParser(...).parseFragment().text`. Replace all direct use of same with the new `unEscapeHtml` getter.
=> fix: ambersand in podcast title shown as `&amp`
