ubuntu-flutter-community/musicpod

lib/l10n/app_sv.arb

Add Swedish Translation

---

lib/app/common/audio_page.dart
lib/app/common/audio_page_control_panel.dart
lib/app/common/audio_tile.dart
lib/app/music_app.dart
lib/app/player_model.dart
lib/app/player_view.dart
lib/app/podcasts/podcasts_page.dart
lib/main.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
pubspec.yaml

We're now using the awesome media_kit by @alexmercerind :+1:

Switch from audioplayers to mediakit

---

lib/app/music_app.dart
lib/app/podcasts/podcast_model.dart
lib/app/podcasts/podcasts_page.dart
lib/data/podcast_genre.dart
lib/main.dart
lib/service/podcast_service.dart
pubspec.yaml

[Bildschirmaufzeichnung vom 13.03.2023, 00:47:43.webm](https://user-images.githubusercontent.com/15329494/224581520-fa304488-d531-49b9-94d0-1dd4f8b9275b.webm)
Also remove pubspec version, snap just has git commit as version

Don't await podcast init

---

lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/l10n/app_ru.arb
lib/l10n/app_zh.arb

@Feichtmeier  I'm translating your app in French, and I noticed the `music` entry was duplicated :)

Remove duplicated music l10n arb key

---

lib/main.dart
lib/service/local_audio_service.dart

Load audio metadata in an isolate

---

lib/app/common/constants.dart
lib/app/common/country_popup.dart
lib/app/common/search_field.dart
lib/app/local_audio/local_audio_model.dart
lib/app/local_audio/local_audio_page.dart
lib/app/local_audio/local_audio_search_page.dart
lib/app/local_audio/titles_view.dart
lib/app/podcasts/podcast_model.dart
lib/app/podcasts/podcast_search_page.dart
lib/app/podcasts/podcasts_page.dart
lib/app/radio/radio_model.dart
lib/app/radio/radio_page.dart
lib/app/radio/tag_popup.dart

Consolidate search and headers

---

lib/app/common/round_image_container.dart
lib/app/local_audio/artists_view.dart
lib/app/local_audio/local_audio_search_page.dart
lib/l10n/app_en.arb
lib/utils.dart

Fix random color disco for artists without image

---

lib/service/library_service.dart

Reuse working dir function in libraryservice

---

lib/app/common/audio_page_body.dart
lib/app/local_audio/album_view.dart
lib/app/local_audio/artists_view.dart
lib/app/local_audio/local_audio_page.dart
lib/app/local_audio/local_audio_search_page.dart
lib/app/local_audio/titles_view.dart
lib/app/podcasts/podcast_search_page.dart
lib/app/podcasts/podcasts_page.dart

Remove models from lower widgets where possible

---

lib/app/local_audio/titles_view.dart
lib/app/player/bottom_player.dart
lib/app/player/full_height_player.dart
lib/app/player/player_controls.dart
lib/app/player/player_model.dart
lib/app/player/player_view.dart
lib/app/player/queue_popup.dart
lib/app/player/volume_popup.dart
lib/l10n/app_en.arb

Create a queue for everything and show queue in player view

---

lib/app/common/audio_page_body.dart
lib/app/common/audio_tile.dart
lib/app/local_audio/titles_view.dart

Continue playing in an AudioPage from index onwards

---

lib/app/player/player_model.dart
lib/utils.dart

fix: mpris metadata on startup

---

lib/app/app.dart
lib/app/library_model.dart
lib/main.dart
lib/service/library_service.dart
lib/service/local_audio_service.dart
lib/service/podcast_service.dart
lib/service/radio_service.dart

Dispose services on app close

---

lib/app/common/like_button.dart
lib/app/common/offline_page.dart
lib/app/player/like_icon_button.dart
lib/app/radio/station_page.dart
pubspec.yaml

[Capture vidéo du 2023-07-30 21-21-46.webm](https://github.com/ubuntu-flutter-community/musicpod/assets/36476595/7d702591-4eba-4068-8c24-55adbfa04802)

feat: use animated heart and star icons

---

lib/app/player/player_model.dart

fix: Enable shuffle on an album with one track locks up UI

---

lib/app/player/player_model.dart

fix: Reaching the end of an album causes repeat from last clicked track

---

lib/app/app.dart
lib/app/common/audio_page.dart
lib/app/common/offline_page.dart
lib/app/local_audio/local_audio_page.dart
lib/app/playlists/playlist_dialog.dart
lib/app/podcasts/podcasts_page.dart
lib/app/radio/radio_page.dart
lib/musicpod.dart

Follow new gtk4 gnome paned look

---

snap/snapcraft.yaml

Update LD_LIBRARY_PATH in the build-environment to find the staged libmpv fixes #71

Update LD_LIBRARY_PATH in the build-environment

---

lib/app/app.dart
lib/app/player/bottom_player.dart
lib/app/player/full_height_player.dart
pubspec.lock
pubspec.yaml

- full screen: if video just show the video full height
- bottom player: decrease fallback icon size

player improvements

---

lib/app/podcasts/podcast_audio_tile.dart

improve podcast tile differentiation

---

lib/app/player/full_height_player.dart
lib/app/player/player_model.dart

make isVideo work

---

lib/app/app.dart
lib/app/player/player_model.dart
lib/service/library_service.dart
linux/my_application.cc

Move disk access out of player model

---

lib/app/app.dart
lib/app/common/audio_page.dart
lib/app/common/audio_page_body.dart
lib/app/common/audio_tile.dart
lib/app/library_model.dart
lib/app/local_audio/local_audio_search_page.dart
lib/app/master_items.dart
lib/app/player/player_model.dart
lib/app/podcasts/podcast_audio_tile.dart
lib/app/podcasts/podcast_page.dart
lib/app/podcasts/podcasts_page.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/service/library_service.dart

Show badge in sidebar for updates

---

lib/app/app.dart
lib/app/library_model.dart
lib/app/local_audio/failed_imports_content.dart
lib/app/local_audio/local_audio_page.dart
lib/constants.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/service/library_service.dart

Feature request: Ignore failed to import warning on startup

---

snap/snapcraft.yaml

work around pub get stack overflow # https://github.com/dart-lang/sdk/issues/51068#issuecomment-1396588253

work around pub get stack overflow

---

lib/app/app.dart
lib/main.dart
lib/musicpod.dart
lib/service/local_audio_service.dart
linux/my_application.cc
pubspec.lock
pubspec.yaml

load audio from path

---

lib/app/common/audio_card.dart
lib/app/common/safe_network_image.dart
lib/app/xdg_cache_manager.dart
lib/constants.dart
pubspec.lock
pubspec.yaml

but this time with the cache manager to fix it for multiple users
also remove the shimmer effect on loading tiles, tends to be a bit annoying

Use cache network image again

---

lib/src/library/library_service.dart
lib/src/local_audio/cache_dialog.dart
lib/src/local_audio/local_audio_page.dart
lib/src/settings/settings_tile.dart

Move write and read cache to isolates

---

lib/src/library/library_service.dart

Do not read cache if disabled later

---

lib/src/l10n/app_de.arb
lib/src/l10n/app_en.arb
lib/src/podcasts/podcasts_page.dart
pubspec.lock

Add podcasts lib page

---

lib/src/l10n/app_de.arb
lib/src/l10n/app_en.arb
lib/src/podcasts/podcast_model.dart
lib/src/podcasts/podcasts_page.dart

add updates only toggle in podcasts

---

pubspec.lock
pubspec.yaml

Fix wrong station strings

---

README.md
lib/constants.dart
lib/src/app/master_items.dart
lib/src/common/audio_page_body.dart
lib/src/data/audio.dart
lib/src/l10n/app_de.arb
lib/src/l10n/app_en.arb
lib/src/library/library_model.dart
lib/src/library/library_service.dart
lib/src/podcasts/download_button.dart
lib/src/podcasts/download_model.dart
lib/src/podcasts/podcast_audio_tile.dart
lib/src/podcasts/podcast_model.dart
lib/src/podcasts/podcast_page.dart
lib/src/podcasts/podcasts_collection_body.dart
lib/utils.dart
pubspec.lock
pubspec.yaml

feature: download podcasts

---

lib/src/common/audio_card.dart

its blurry in light mode with some images

Dont use border on audio cards

---

.github/workflows/appimage.yml
AppImageBuilder.yml

I've connected everything ant tested on my local machine with [act tool](https://github.com/nektos/act) and it seems to work.
I have to test it on my repo, to connect it with GitHub Actions, but you could try it too in the meantime.
Oh, and if you are celebrating today's Christmas, merry Christmas 🎄

appimage build GithubAction

---

lib/src/player/bottom_player.dart
lib/src/player/full_height_player.dart
lib/src/player/very_narrow_bottom_player.dart

Add swiping to change player view on Android

---

lib/src/app/master_detail_page.dart
lib/src/common/audio_page_body.dart
lib/src/local_audio/album_view.dart
lib/src/local_audio/local_audio_search_page.dart
lib/src/player/player_model.dart
lib/src/player/player_service.dart
lib/src/podcasts/podcasts_collection_body.dart
lib/src/podcasts/podcasts_discover_grid.dart

don't create new queues each time

---

lib/src/player/player_model.dart
lib/src/player/player_service.dart
lib/src/player/player_view.dart
pubspec.lock
pubspec.yaml

remove player dominant color

---

lib/src/player/player_model.dart
lib/src/player/player_service.dart
lib/src/player/player_view.dart
pubspec.lock
pubspec.yaml

Revert player color removal

---

lib/src/podcasts/podcasts_discover_grid.dart

small preps for podcast index

---

lib/constants.dart
lib/src/app/app.dart
lib/src/common/icons.dart
lib/src/data/podcast_genre.dart
lib/src/l10n/app_de.arb
lib/src/l10n/app_en.arb
lib/src/library/library_service.dart
lib/src/podcasts/podcast_model.dart
lib/src/podcasts/podcast_service.dart
lib/src/podcasts/podcasts_page.dart
lib/src/settings/settings_button.dart
lib/src/settings/settings_dialog.dart
lib/src/settings/settings_model.dart
pubspec.lock
pubspec.yaml
test/podcast_service_test.dart

Add podcast index option

---

lib/src/app/app.dart
lib/src/patch_notes/patch_notes.dart

fix Feature Request: Spacebar Starts and Stops Audio Playback

---

lib/utils.dart

Opus support

---

lib/src/library/playlist_page.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
macos/Podfile.lock
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

Feature Request: Support drag and drop from File manager

---

lib/utils.dart

MusicPod can't read AAC files

---

lib/src/common/icy_image.dart
lib/src/common/like_button.dart
lib/src/external_path/external_path_service.dart
lib/src/l10n/app_de.arb
lib/src/l10n/app_en.arb
lib/src/library/manual_add_dialog.dart
pubspec.lock
pubspec.yaml

Support manual m3u playlist import

---

lib/src/external_path/external_path_service.dart
pubspec.lock
pubspec.yaml

Add .pls import option

---

lib/constants.dart
lib/src/common/audio_page.dart
lib/src/common/audio_page_body.dart
lib/src/common/audio_tile_header.dart
lib/src/l10n/app_de.arb
lib/src/l10n/app_en.arb
lib/src/local_audio/local_audio_model.dart
lib/src/local_audio/titles_view.dart
lib/src/podcasts/podcasts_discover_grid.dart
lib/src/settings/settings_service.dart

Sort titles view by title, localize load more

---

lib/src/common/confirmation_dialog.dart
lib/src/podcasts/podcasts_collection_body.dart

fix: queueConfirmMessage duplicated

---

lib/get.dart
lib/main.dart
lib/src/app/app.dart
lib/src/app/app_model.dart
lib/src/app/musicpod.dart
lib/src/library/library_model.dart
lib/src/library/manual_add_dialog.dart
lib/src/local_audio/local_audio_model.dart
lib/src/player/player_model.dart
lib/src/podcasts/download_model.dart
lib/src/podcasts/podcast_model.dart
lib/src/radio/radio_model.dart
lib/src/settings/settings_model.dart
pubspec.lock
pubspec.yaml

replace ubuntu_service with get_it

---

lib/common.dart
lib/src/app/master_detail_page.dart
lib/src/common/copy_clipboard_content.dart
lib/src/common/snackbars.dart
lib/src/library/liked_audio_page.dart
lib/src/library/playlist_page.dart
lib/src/local_audio/album_page.dart
lib/src/local_audio/album_view.dart
lib/src/local_audio/artist_page.dart
lib/src/local_audio/titles_view.dart
lib/src/player/bottom_player_title_artist.dart
lib/src/player/full_height_title_and_artist.dart
lib/src/player/player_utils.dart
lib/src/player/up_next_bubble.dart
lib/src/radio/radio_history_list.dart
lib/src/radio/station_card.dart
lib/src/radio/station_page.dart

Refactor player_utils

---

lib/main.dart
lib/src/app/master_detail_page.dart
lib/src/app/splash_screen.dart
lib/src/common/audio_page.dart
lib/src/common/common_widgets.dart
lib/src/common/offline_page.dart
lib/src/local_audio/artist_page.dart
lib/src/local_audio/genre_page.dart
lib/src/local_audio/local_audio_page.dart
lib/src/local_audio/local_audio_search_page.dart
lib/src/player/full_height_player.dart
lib/src/podcasts/podcasts_page.dart
lib/src/radio/radio_discover_page.dart
lib/src/radio/radio_page.dart
lib/src/radio/radio_search_page.dart
lib/src/radio/station_page.dart

Move showWindowControls to HeaderBar

---

lib/main.dart
lib/src/app/app.dart
lib/src/data/audio.dart
lib/src/library/library_model.dart
lib/src/local_audio/local_audio_model.dart
lib/src/player/player_model.dart
lib/src/podcasts/podcast_model.dart
lib/src/podcasts/podcast_service.dart
lib/src/podcasts/podcasts_page.dart
lib/src/radio/radio_model.dart
lib/src/settings/settings_model.dart
test/radio_service_test.dart

- don't overwrite subs
- init page independent ViewModels in main
- create factory constructors for audios from radio and podcasts
- add comments for clarification

ViewModel clean ups

---

lib/main.dart
lib/src/data/audio.dart
lib/src/external_path/external_path_service.dart
lib/src/player/player_model.dart
lib/src/player/player_service.dart
lib/src/radio/radio_model.dart
lib/src/radio/radio_page.dart
lib/src/radio/radio_service.dart
test/radio_service_test.dart

Radio reconnect improvements, fix external path service

---

lib/src/player/player_model.dart
lib/src/player/player_service.dart
lib/src/player/volume_popup.dart

Feature request: Retain volume level between application launches

---

lib/src/player/full_height_player.dart
lib/src/player/full_height_player_top_controls.dart
lib/src/radio/open_radio_discover_page_button.dart
macos/Podfile.lock
pubspec.lock
pubspec.yaml

fix: Radio page is one large block of colour

---

lib/src/player/bottom_player.dart
lib/src/player/bottom_player_image.dart
lib/src/player/full_height_player.dart
lib/src/player/full_height_player_top_controls.dart
lib/src/player/player_main_controls.dart
lib/src/player/player_view.dart
lib/src/player/queue_button.dart

Swap out controls depending on audiotype and queue length

---

lib/src/common/share_button.dart
lib/src/common/snackbars.dart
lib/src/radio/station_page.dart
macos/Podfile.lock
pubspec.lock

fix: Clipboard copy dialog disappears too quickly

---

lib/src/common/stream_provider_share_button.dart
lib/src/player/view/player_track.dart

Localize amazon links

---

lib/src/common/common_widgets.dart
lib/src/player/view/player_track.dart

Replace slider with indicator for duration < 30

---

lib/src/playlists/view/add_to_playlist_dialog.dart

Newly created playlists doesn't show up

---

lib/src/common/icons.dart
lib/src/common/like_button.dart

Align "search" icons in context menu

---

lib/src/common/custom_track_shape.dart
lib/src/player/view/player_track.dart
lib/src/player/view/volume_popup.dart
lib/src/theme.dart

Increase light volume slider contrast

---

flatpak/org.feichtmeier.Musicpod.appdata.xml

Please double-check this that it says GPL

Fix the Liscense 

---

.github/workflows/appimage.yml
.github/workflows/ci.yaml
.github/workflows/snap.yaml
lib/src/app/view/app.dart
lib/src/app/view/master_detail_page.dart
lib/src/common/audio_autocomplete.dart
lib/src/common/country_auto_complete.dart
lib/src/common/language_autocomplete.dart
lib/src/player/view/full_height_player.dart
lib/src/player/view/volume_popup.dart
lib/src/podcasts/view/podcast_genre_autocomplete.dart
lib/src/radio/view/tag_auto_complete.dart
lib/src/settings/view/about_page.dart
lib/src/settings/view/licenses_page.dart
lib/src/settings/view/settings_dialog.dart
lib/theme_data_x.dart
macos/Podfile.lock
pubspec.lock
pubspec.yaml
snap/snapcraft.yaml

Reverts ubuntu-flutter-community/musicpod#767
Due to heavy graphic bugs we can not upgrade yet

Revert "Upgrade to flutter 3.22"

---

lib/src/common/country_auto_complete.dart
lib/src/podcasts/view/podcasts_control_panel.dart

fix: Country-menu is too narrow

---

lib/date_time_utils.dart
lib/src/podcasts/view/podcast_audio_tile.dart

fix: date format error with unknown locale

---

lib/app/connectivity_model.dart
lib/common/data/audio.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/radio/view/radio_page_tag_bar.dart
needs_translation.json

some stations send a bunch of weird tags, this is hard to make pretty, thus show only 25 or a disclaimer->expand

fix: mitigate radio station tag spam

---

lib/app/view/master_detail_page.dart
lib/app/view/splash_screen.dart
lib/common/view/audio_tile.dart
lib/common/view/audio_tile_image.dart
lib/common/view/cover_background.dart
lib/common/view/icy_image.dart
lib/compute_isolate.dart
lib/local_audio/cover_store.dart
lib/local_audio/local_audio_model.dart
lib/local_audio/local_audio_service.dart
lib/local_audio/view/album_page.dart
lib/local_audio/view/album_view.dart
lib/local_audio/view/genres_view.dart
lib/local_audio/view/local_audio_body.dart
lib/local_audio/view/local_cover.dart
lib/persistence_utils.dart
lib/player/player_service.dart
lib/player/view/blurred_full_height_player_image.dart
lib/player/view/bottom_player_image.dart
lib/player/view/bottom_player_title_artist.dart
lib/player/view/full_height_player_image.dart
lib/player/view/player_fall_back_image.dart
lib/player/view/super_network_image.dart
test/podcast_service_test.dart

fix: do not load covers at start

---

lib/local_audio/local_audio_service.dart
lib/local_audio/view/album_page.dart
pubspec.yaml

fix: disable read/write of local cache until setting and dialog are back

---

lib/app/view/app.dart
lib/common/data/audio.dart
lib/common/view/audio_tile_image.dart
lib/local_audio/cover_store.dart
lib/local_audio/local_audio_model.dart
lib/local_audio/local_audio_service.dart
lib/local_audio/view/album_page.dart
lib/local_audio/view/album_view.dart
lib/local_audio/view/artist_page.dart
lib/local_audio/view/artists_view.dart
lib/local_audio/view/local_audio_body.dart
lib/local_audio/view/local_audio_page.dart
lib/local_audio/view/local_audio_search_page.dart
lib/local_audio/view/local_cover.dart
lib/player/player_mixin.dart
lib/player/player_service.dart
lib/player/view/bottom_player_image.dart
lib/player/view/full_height_player_image.dart
lib/playlists/view/playlist_page.dart

fix: remove audio list duplications

---

lib/app/view/system_tray.dart
lib/constants.dart

fix: linux tray icon

---

lib/search/view/sliver_radio_search_results.dart

fix: Must search by name before searching by tag, country, or language

---

lib/local_audio/local_audio_service.dart

fix: The presence of a lost+found folder makes musicpod unable to load the users music library

---

lib/local_audio/local_audio_service.dart

fix: onError callback

---

lib/common/data/audio.dart
lib/common/view/audio_tile.dart
lib/common/view/like_icon.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/player/view/player_main_controls.dart
lib/radio/view/next_station_button.dart
lib/search/search_model.dart
needs_translation.json

feat(radio): add return to livestream & play similar station buttons

---

lib/local_audio/view/failed_imports_content.dart

fix: linux failed import snackbar

---

pubspec.lock
pubspec.yaml

fix: update frb_plugins dependency

---

lib/l10n/app_it.arb

@Feichtmeier 
Please merge. Thanks.

Update Italian language

---

lib/common/view/audio_type_is_playing_indicator.dart
lib/constants.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/local_audio/view/local_audio_page.dart
lib/podcasts/view/podcasts_page.dart
lib/radio/view/radio_page_icon.dart
lib/settings/settings_model.dart
lib/settings/settings_service.dart
lib/settings/view/settings_page.dart
needs_translation.json

Co-authored-by: Davide Bianco <dn.bianco03@gmail.com>

feat: bring back the audio type playing indicator by @HrX03

---

lib/common/logging.dart
lib/library/library_model.dart
lib/podcasts/podcast_service.dart
lib/search/view/search_page.dart
lib/search/view/sliver_podcast_search_results.dart
lib/search/view/sliver_radio_search_results.dart

fix: podcast and radio search jumping on scroll

---

lib/common/view/country_auto_complete.dart
lib/common/view/language_autocomplete.dart
lib/common/view/search_input.dart
lib/common/view/theme.dart
lib/search/search_model.dart
lib/search/view/audio_type_filter_button.dart
lib/search/view/podcast_search_input_prefix.dart
lib/search/view/search_page.dart
lib/search/view/search_page_input.dart
lib/search/view/sliver_podcast_filter_bar.dart
lib/search/view/sliver_search_type_filter_bar.dart

https://github.com/user-attachments/assets/49ca750b-6f51-4d24-a821-33a9117f0aad

feat: redesign the podcast search filtering

---

lib/patch_notes/patch_notes_dialog.dart

fix: changelog links are unclickable

---

lib/main.dart
lib/player/player_model.dart
lib/player/player_service.dart
lib/radio/online_art_model.dart
lib/radio/online_art_service.dart
lib/radio/radio_model.dart
lib/radio/view/radio_history_list.dart
lib/radio/view/radio_history_tile.dart
lib/radio/view/radio_history_tile_image.dart
lib/radio/view/station_page.dart
needs_translation.json

fix: radio history tile images after new station uuid mapping

---

lib/common/view/theme.dart
lib/settings/view/settings_page.dart

https://github.com/user-attachments/assets/d68bd906-9074-47ab-a449-267b15f45d52

fix: last fm improve settings UI

---

lib/external_path/external_path_service.dart
lib/local_audio/local_audio_service.dart
lib/local_audio/local_cover_service.dart
lib/playlists/view/playlist_page.dart
pubspec.lock
pubspec.yaml

feat: improve local audio import speed by updating audio_metadata_reader

---

lib/local_audio/local_audio_model.dart
lib/local_audio/local_audio_service.dart
lib/local_audio/view/artists_view.dart
lib/local_audio/view/local_audio_body.dart
lib/local_audio/view/local_audio_page.dart
lib/local_audio/view/local_audio_view.dart
lib/search/search_model.dart
lib/search/search_type.dart
lib/search/view/sliver_local_search_results.dart
lib/search/view/sliver_search_type_filter_bar.dart

feat: add support for "Album Artist"

---

lib/local_audio/local_cover_service.dart

feat: also use the cover image stored inside the album folders

---

lib/player/player_service.dart

https://github.com/user-attachments/assets/aac37011-1493-45d1-9bea-c25819050cdd
Fixes #1060

fix: repeat single should not disable traversing with next/prev buttons

---

lib/player/view/bottom_player.dart
lib/player/view/full_height_player_top_controls.dart

fix: remove volume slider for mobile

---

lib/common/data/audio.dart
lib/local_audio/local_audio_view.dart
lib/local_audio/view/local_audio_body.dart
lib/search/search_model.dart
lib/search/search_type.dart
lib/search/view/sliver_local_search_results.dart
lib/search/view/sliver_search_type_filter_bar.dart

fix: disable album artist filter until provided by audio_metadata_reader

---

lib/common/data/audio.dart

fix: Make local music genre menu case insensitive

---

lib/player/player_service.dart
lib/player/view/queue_button.dart

feat: use real shuffle

---

lib/local_audio/local_cover_service.dart

fix: Album cover defaults to the back cover if there are two embedded images in a file

---

lib/app/view/mobile_page.dart

feat: Add PopScope to monitor MobileBottomBar (#1146)

feat: Add PopScope to monitor MobileBottomBar (#1146)

---

lib/common/view/avatar_play_button.dart
lib/l10n/app_de.arb
lib/l10n/app_en.arb
lib/player/player_model.dart
lib/player/player_service.dart
lib/player/view/queue/queue_dialog.dart
needs_translation.json

https://github.com/user-attachments/assets/45a6db5e-ca5d-4acb-8670-708bdf995bc4
Fixes #1157

feat: add clear queue button

---

lib/common/view/adaptive_container.dart
lib/common/view/adaptive_list_tile.dart
lib/common/view/audio_tile.dart
lib/common/view/audio_tile_image.dart
lib/common/view/ui_constants.dart
lib/extensions/media_file_x.dart
lib/external_path/external_path_service.dart
lib/local_audio/local_audio_service.dart
lib/playlists/view/playlist_page.dart
lib/podcasts/view/podcast_page.dart
lib/podcasts/view/podcast_page_title.dart
pubspec.lock
pubspec.yaml

fix: fail to import music with no tags

---

lib/app/view/desktop_home_page.dart
lib/app/view/mobile_page.dart
lib/common/view/sliver_app_bar_bottom_space.dart
lib/common/view/sliver_audio_page_control_panel.dart
lib/l10n/app_en.arb
lib/podcasts/podcast_model.dart
lib/podcasts/view/podcast_page.dart
lib/podcasts/view/podcast_state_stream_handler.dart
lib/podcasts/view/sliver_podcast_page_search_field.dart
lib/settings/view/about_page.dart
lib/settings/view/licenses_page.dart
lib/settings/view/settings_dialog.dart
lib/settings/view/settings_page.dart
needs_translation.json

https://github.com/user-attachments/assets/00de6b5f-e62e-4d38-8728-0b081c0be67a
Fixes #1166

feat: searching within a podcast

---

lib/player/player_model.dart
lib/player/player_service.dart

https://github.com/user-attachments/assets/661afc3d-5143-4d9e-9107-6b399ff70c87
Fixes #90

fix: shuffle doesn't work with local tracks

---

lib/app/window_size_to_settings_listener.dart
lib/extensions/shared_preferences_x.dart
lib/register.dart

feat: persist window size

---

lib/common/logging.dart

chore: adjust printMessageInDebugMode()

---

lib/expose/expose_service.dart
lib/register.dart

fix: discord disabling

---

lib/extensions/media_file_x.dart

fix: AAC files using M4A wrapper not loading properly

---

lib/app/view/desktop_home_page.dart
lib/common/view/icons.dart
lib/custom_content/custom_content_model.dart
lib/custom_content/view/custom_playlists_section.dart
lib/library/library_model.dart
lib/library/library_service.dart
lib/local_audio/local_audio_model.dart
lib/local_audio/local_audio_service.dart
lib/local_audio/view/playlists_view.dart
lib/player/view/queue/queue_body.dart
lib/player/view/queue/queue_dialog.dart
lib/playlists/view/edit_playlist_dialog.dart
lib/playlists/view/playlist_page.dart
lib/podcasts/view/podcast_collection_control_panel.dart
lib/radio/view/radio_lib_page.dart
lib/register.dart
lib/settings/settings_model.dart
lib/settings/settings_service.dart
lib/settings/view/local_audio_section.dart
test/local_audio_service_test.dart
test/podcast_service_test.mocks.dart

chore: connect playlist import and local audios

---

lib/common/view/audio_tile_option_button.dart
lib/common/view/avatar_play_button.dart
lib/extensions/podcast_x.dart
lib/podcasts/podcast_model.dart
lib/podcasts/podcast_service.dart
lib/podcasts/view/lazy_podcast_loading_page.dart
lib/podcasts/view/lazy_podcast_page.dart
lib/podcasts/view/podcast_page.dart
lib/podcasts/view/podcast_page_control_panel.dart
lib/podcasts/view/podcast_page_search_button.dart
lib/podcasts/view/podcast_sub_button.dart
macos/Runner.xcodeproj/project.pbxproj

https://github.com/user-attachments/assets/a876451c-f22e-4224-a111-bfe8421d11e9

feat: show podcast pages immediately, then load the episodes

---

lib/extensions/media_file_x.dart

fix: MusicPod not loading .opus files after the last update

---

lib/extensions/shared_preferences_x.dart
lib/l10n/app_en.arb
lib/local_audio/local_audio_service.dart
lib/player/player_service.dart
lib/settings/settings_model.dart
lib/settings/settings_service.dart
lib/settings/view/local_audio_section.dart

fix: albums are split if the songs in it have different artists

---

lib/app/view/back_button_wrapper.dart
lib/app/view/desktop_musicpod_app.dart
lib/common/view/round_image_container.dart
lib/local_audio/view/artist_image.dart
lib/local_audio/view/artist_page.dart
lib/local_audio/view/artists_view.dart
lib/local_audio/view/genres_view.dart
lib/local_audio/view/playlists_view.dart

feat: navigate back with the back mouse button in windows and macos

---

lib/common/data/audio_type.dart
lib/common/view/theme.dart
lib/common/view/ui_constants.dart
lib/search/view/audio_type_filter_button.dart
lib/search/view/podcast_search_input_prefix.dart
lib/search/view/search_page_input.dart

Thanks @EricApostal for the idea

fix: shorten audiotype switcher clicks for desktop
